name: ula-prior
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pytorch=2.8
  - torchvision
  - numpy
  - scipy
  - pillow
  - matplotlib
  - pyyaml
  - mpi4py
  - pip
  - setuptools<81
  - pip:
      - blobfile
      - ehtim==1.2.10
      - torchkbnufft==1.5.2
      - "wandb>=0.23,<0.24"
